### Cadastrar despesa
POST http://localhost:3333
Content-Type: application/json

{
    "descricao" : "Conta de luz",
    "preco" : 50
}

### Listar despesas
GET http://localhost:3333/listar

### Calcular Media
GET http://localhost:3333/calcular